name: pandas_workshop
channels:
  - conda-forge
dependencies:
  - python>=3.11.0,<3.16.0
  - jupyterlab>=4.6.4
  - matplotlib=3.11.2
  - numpy>=2.4.6
  - pandas=3.0.6
  - requests>=2.34.2
  - scipy>=1.17.1
  - seaborn=0.13.2
