[project]
name = "pandas-workshop"
version = "5.0.0"
description = "An introductory workshop on pandas created by Stefanie Molin"
readme = "README.md"
license-files = ["LICENSE"]
authors = [
    { name = "Stefanie Molin", email = "pandas-workshop@stefaniemolin.com" },
]
requires-python = ">=3.11"
dependencies = [
    "jupyterlab>=4.6.4",
    "matplotlib==3.11.2",
    "numpy>=2.4.6",
    "pandas==3.0.6",
    "requests>=2.34.2",
    "seaborn==0.13.2",
]

[dependency-groups]
slides = ["nbmerge>=0.0.4"]
